name: pysecrets

on:
  workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest
      steps:
        - name: Test env vars for python
          run: python -c 'import os; print(os.environ)'
          env:
            MYSECRET: ${{ secrets.MYSECRET }}
            